### ISSUE TITLE
Enabling integration in https sites

### ISSUE THREAD

**Issue by lpalbou** [geneontology/wc-gocam-viz#1]
The gocam widget fetch data through barista (http only). Https websites such as the Alliance can only fetch data from https origins for security reasons.

To allow the gocam widget to be integrated in the alliance website (or any https origin), one of these actions needs to be done:

- [ ] make barista https; this would help other projects and go a long way towards progressively transitioning all of resources as https (GOLr next in line). As long as those steps are not done, both the go website and all the Noctua suite can not be secured. Requires @kltm time as no access.

- [ ] use the GO API, only https endpoint to date, as a proxy to query barista. IMO, it's a workaround, but depending of longer term vision, this could be a first step towards centralizing all queries through a unique API, which I would be in favor. Requires @lpalbou time.

**Comment by cmungall** [comment]
Thanks for this laying this out. I would opt for the 2nd, use the GO API to proxy to barista (with a view to having more native logic in python later).

We should design the API such that it gives us flexibility later. I don't think we want to be tied to minerva-json response blob forever; we want jsons that are more suited to the client-side task (e.g. showing GO-enhanced integration graph)

How about something like

`/api/barista/model/{id}`

with a view to something like

`/api/interaction-graph/model/{id}`

as well as routes to retrieve supersets of models, e.g. all models for a BP superimposed, etc

does that make sense?

**Comment by lpalbou** [comment]
This is currently done and proxy by the GO-CAM API.

Working for now, but ideally something to be consolidated behind a single GO API.

I still recommend https to be done across the platform (golr, barista, sparql, as well as panther website)
