### ISSUE TITLE
handover of pathway widget

### ISSUE THREAD

**Issue by cmungall** [geneontology/wc-gocam-viz#3]

**Comment by cmungall** [comment]
update from call

need to 2 more meetings with @dustine32 and Tremayne (needs to be added to the group)

**Comment by cmungall** [comment]
this has two parts:

 - go-cam view
 - reactome view

also need meeting specific to alliance integration

**Comment by lpalbou** [comment]
@lpalbou organize 2h on monday / tuesday

**Comment by kltm** [comment]
@dustine32 and at @tmushayahama sound like they're feeling good about this.
