### ISSUE TITLE
Add "has_input" and "has_output" relation symbols to legend

### ISSUE THREAD

**Issue by dustine32** [geneontology/wc-gocam-viz#34]
In this [GO-CAM model](http://noctua.geneontology.org/editor/graph/gomodel:62f58d8800003012?) for [Mouse Itpr1](https://www.alliancegenome.org/gene/MGI:96623#pathways), the `has_input` and `has_output` relations (circled) are not shown in the legend, making their meaning ambiguous to the viewer:
![image](https://github.com/geneontology/wc-gocam-viz/assets/2678599/c1dc9be2-b808-4eb8-8732-1b22b1a3471e)

We should add these two relation symbols to the legend.

Reported by Paul Sternberg and @thomaspd. Tagging @tmushayahama and @kltm to determine who should make the code change.

**Comment by kltm** [comment]
@pgaudet bundling this into AGR project, as noticed by PI.

**Comment by kltm** [comment]
@dustine32 I'm not sure who is most familiar with the codebase at this point. I'm guessing this is a small change?
I'm guessing that @dustine32 @tmushayahama or @pkalita-lbl would be able to quickfix, but I'm not sure who has this in their head the most. I'll ask on slack.

**Comment by tmushayahama** [comment]
This is already working up-to-date on the web-component, I don't know what version of the component the agr-ui is using. As you can see from the workbench example, the legend shows the has_output and has_input. So might be a simple version bump on the agr-ui site

![image](https://github.com/geneontology/wc-gocam-viz/assets/2273929/19440a4e-1a64-4ea4-8e30-407b4f02a1f9)

the url is this 
http://noctua-dev.berkeleybop.org/workbench/noctua-alliance-pathway-preview/?model_id=gomodel%3A61f34dd300001044

tagging @kltm @pkalita-lbl @dustine32

**Comment by dustine32** [comment]
Sorry @tmushayahama for making you dig into something that should have been obvious to me! You're right. The latest `geneontology/wc-gocam-viz` npm version is `1.0.0` and `agr_ui` [is currently on](https://github.com/alliance-genome/agr_ui/blob/7e182089fb44c774a58552c54ab399acbf85259f/package.json#L15C7-L15C32) `0.0.51`.

**Comment by kltm** [comment]
Okay, so what is the action here? If this "works" in our version, is the action to make a ticket on the AGR tracker?

**Comment by dustine32** [comment]
@kltm Yup! Just created: https://github.com/alliance-genome/agr_ui/issues/1272

**Comment by kltm** [comment]
Cheers! Closing out here.

**Comment by vanaukenk** [comment]
Hi - re-opening this ticket as it came up in discussion on the Swiss-Prot GO-CAM call today.
@tmushayahama - let's touch base about this at the end of today's workbenches call.

**Comment by kltm** [comment]
@tmushayahama @vanaukenk I see this in the "Done" category, but is "Open". What is the current state here?

Also, does this have any relation to the items here https://github.com/orgs/geneontology/projects/160/views/1 ?

**Comment by vanaukenk** [comment]
Closing as I believe this work is done and implemented in the versions on the Alliance and both Noctua production and dev.
