### ISSUE TITLE
possible bug Protein complex

### ISSUE THREAD

**Issue by ValWood** [geneontology/wc-gocam-viz#36]
@vanaukenk 

I have made a model with a protein complex (this will become the  respiratory chain once the other complexes are curated in complex portal)

I expected to be able to expand the complex in the widget to see the individual subunits but I can't:

<img width="1267" alt="Screenshot 2024-05-15 at 11 53 36" src="https://github.com/geneontology/wc-gocam-viz/assets/7359272/486c1dbb-f534-4646-b3e1-cae67255b221">

Is this a problem with the viewer or with our input file?

Also, is there a way to get  the label of the complex display as the name rather than the identifier? (I guess we probably need to do similar to what we did for PRO IDs)

CC @kimrutherford

**Comment by kimrutherford** [comment]
> Also, is there a way to get the label of the complex display as the name rather than the identifier? (I guess we probably need to do similar to what we did for PRO IDs)

I've changed the PomBase GPI writing code to put the complex name in column 3 / DB_Object_Name.  It will be in the GPI file from tomorrow morning (UK time).  I hope that helps.

**Comment by kimrutherford** [comment]
We include the complex members in column 9 / `Protein_Containing_Complex_Members`.

@ValWood Are the complex members visible in Noctua?

**Comment by ValWood** [comment]
I don't see any way to see them, so I'm not sure @vanaukenk should be there?
