### ISSUE TITLE
Add special toggle to choose minerva/system instance as source of model data

### ISSUE THREAD

**Issue by dustine32** [geneontology/wc-gocam-viz#4]
From Alliance Pathways 2021-11-02 call, suggested by @cmungall.

Add a little toggle to the pathway viewer widget so that devs and curators can look at models in either prod or dev minerva instances. The toggle would likely go here:

![image](https://user-images.githubusercontent.com/2678599/139946125-42014f04-84cb-4224-a20b-906a7d16a565.png)

This toggle should only be accessible on the sandbox instance available at http://proto.geneontology.xyz/

Tagging @kltm @tmushayahama

**Comment by vanaukenk** [comment]
@kltm @cmungall @dustine32 

I'm not sure if this is still needed?

If not, please feel free to close the ticket.  Thx.

**Comment by kltm** [comment]
Whoops--didn't know about this site either. The API is going to be moving on. @dustine32 Could you mothball/freeze this one out? 
That said, as this is about a demo/test site that was on none of our radars; I think this can be closed.

**Comment by dustine32** [comment]
@vanaukenk @kltm Right, this sandbox hasn't been used for a long while now and we already have the pathway viewer workbenches for both prod and dev Noctua modelstores. I'll close this for now.
