### ISSUE TITLE
Make new release on merged code

### ISSUE THREAD

**Issue by kltm** [geneontology/wc-gocam-viz#47]
Hi, I only see `1.0.1-beta.2` (five months ago) on NPM for this package. Would you guys be able to create a new release with the fix from this PR?

_Originally posted by @dlrice in https://github.com/geneontology/wc-gocam-viz/issues/45#issuecomment-2429451289_

**Comment by pkalita-lbl** [comment]
Version 1.0.1 has been published to NPM:

* https://www.npmjs.com/package/@geneontology/wc-gocam-viz/v/1.0.1
* https://github.com/geneontology/wc-gocam-viz/releases/tag/v1.0.1
