### ISSUE TITLE
Layout of disconnected entities is too close together

### ISSUE THREAD

**Issue by dustine32** [geneontology/wc-gocam-viz#5]
The current layout of the Alliance Pathway Preview places entities with no connections between them too close together, as this example [model](http://noctua-dev.berkeleybop.org/workbench/noctua-gocam-pathway/?model_id=gomodel:MGI_MGI_3028590) shows:
![image](https://user-images.githubusercontent.com/2678599/142074531-a9db62d6-cf2d-4df3-8d77-fd2a98e95b8c.png)

The Pathway View workbench for same [model](http://noctua-dev.berkeleybop.org/workbench/pathwayview/?model_id=gomodel:MGI_MGI_3028590) shows ideal spacing between disconnected entities:
![image](https://user-images.githubusercontent.com/2678599/142074945-f397889e-e0d6-4c19-9c25-21431ae1d0a6.png)

@tmushayahama Would you be able to see how difficult this is to fix?

**Comment by dustine32** [comment]
Noting this request came from @cmungall on the 2021-11-16 Alliance Pathways call.

**Comment by vanaukenk** [comment]
@dustine32 

Another thing I noticed about this model is that in the right-hand panel, none of the BPs are listed; there's only 'others processes' at the top of the list (we should fix that minor typo so it reads 'other processes).

Granted, these types of models likely won't be displayed on the Alliance Pathways section, but is there a specific reason the BP terms aren't displayed above each instance of Mei1?

Thx.

**Comment by kltm** [comment]
Possible this will be practically solved when more models are filtered.

**Comment by vanaukenk** [comment]
Closing this as I think the pathway display is not relevant for gene-centric models.
