### ISSUE TITLE
change synching event between pathway panel and activity-unit info panels

### ISSUE THREAD

**Issue by thomaspd** [geneontology/wc-gocam-viz#9]
Suggestion from Alex Bateman, SAB member. He finds it frustrating that the syncing occurs on a mouse-over event-- if you move the mouse around a bit on the pathway over different nodes in the pathway graph, the activity-unit panel on the right changes very rapidly (and vice versa), which was not intuitive to him. I agree.

He suggested instead that the syncing should occur **on a mouse-click event** instead of a mouse-over. A user has to click on a pathway node (or, in the activity-unit panel, a "gene activity card") in order to highlight and/or scroll to sync between the two panels.

Next step is to discuss on an Alliance pathways call. @dustine32 @tmushayahama

**Comment by vanaukenk** [comment]
Closing this as I think this particular feedback has been addressed and there are other tickets to discuss further improvements to the information panel on the right side of the display.
